# this is the github actions cd.yml file
# here we write code, that runs on a github provisioned ubuntu machine
# what does this do? -
#   we push code to github
#   the code gets deployed in real time to a staging/dev/testing server
name: Deploy Next.js site to Pages
on:
    push:
        branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run deployment script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            ls /var/www/

      - name: Copy setup.sh to server
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "setup.sh"
          target: "/var/www/nextapp_setup/"
# here the folder needed to exist otherwise the github actions fails
# the build keeps failing


      - name: Run deployment script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            bash /var/www/nextapp_setup/setup.sh
            